[package]
name = "trie"
version = "0.1.0"
authors = ["Matt Traudt <sirmatt@ksu.edu>"]
edition = "2018"
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "1.1" }
#serde_json = { version = "1.0" }
